spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/webshop_payment_db
  activemq:
    broker-url: tcp://activemq:61616?jms.prefetchPolicy.all=1
#paypal:
#  redirectUrl: http://1ee69083.ngrok.io/shoopingCart